version: 0.2
env:
  parameter-store:
    DOCKER_REGISTRY_URL: /app/docker/url
    DOCKER_REGISTRY_USERNAME: /app/docker/username
    DOCKER_REGISTRY_PASSWORD: /app/docker/key
phases:
  install:
    runtime_versions:
      python:3.11
      
  pre_build:
      commands:
        - echo "Installing dependencies"
        - pip install -r simple-python-app/requirements.txt
  build:
    commands:
       - echo "Starting the Build...."
       - echo "Procuring required dependencies"
       - cd simple-python-app
       - pwd
       - ls
       - docker build -t "$DOCKER_REGISTRY_URL/govarthan/simple-python-flask-app:latest" .
       - echo "Image build successfully"
       - docker images
       - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
       - docker images
       - docker push "docker.io/govarthan/simple-python-flask-app:latest"
       - echo "Image pushed to registry successfulyy"
  post_build:
    commands:
      - echo "Pipeline completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app

